# mini2cub_res12.yaml
dataset:
  train_root: "miniImagenet"
  train_name: "miniImagenet"
  val_root: "cub_200_new"
  val_name: "cub_200_new"
  test_root: "cub_200_new"
  test_name: "cub_200_new"

dataloader:
  num_workers: 8
  metatrain_iterations: 60000
  metatest_iterations: 600
  val_after: 1000
  meta_batch_size: 4
  metatest_batch_size: 1
  n_way: 5
  k_shot: 1
  k_query: 15
  test_k_query: 1

algo:
  backbone: "res12"
  train_base_lr: 0.01
  base_lr: 0.01
  second_order: false
  T: 5
  T_val: 1
  T_test: 10
  lr: 0.001
  batching_eps: false
  test_adam: false
  grad_clip: 10
  criterion: "ce_loss"
